services:
  data:
    image: mariadb:latest
    container_name: DATA
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./src/create.sql:/docker-entrypoint-initdb.d/create.sql:ro
    networks:
      - savage

  script:
    build: ./docker
    container_name: SCRIPT
    volumes:
      - ./src:/app
    networks:
      - savage
    depends_on:
      - data

  http:
    image: nginx:stable-alpine
    container_name: HTTP
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - savage
    depends_on:
      - script

networks:
  savage:
    driver: bridge